[google]
client_info = '''
{
  "web": {
    "client_id": "DEINE_CLIENT_ID",
    "project_id": "DEIN_PROJEKT",
    "auth_uri": "https://accounts.google.com/o/oauth2/auth",
    "token_uri": "https://oauth2.googleapis.com/token",
    "client_secret": "DEIN_CLIENT_SECRET",
    "redirect_uris": [
      "http://localhost:8501/",
      "https://dashboard-app-7gfyvngg9oy99nqdnzmykn.streamlit.app/"
    ]
  }
}
'''
